<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-27L8JE7" name="com.project.JuneCRMProject.suiteb.NewTest" tests="2" failures="0" timestamp="2021-06-09T18:18:41 IST" time="0.066" errors="1">
  <testcase name="beforeTest" time="0.066" classname="com.project.JuneCRMProject.suiteb.NewTest">
    <error type="java.io.FileNotFoundException" message="D:\AprilWorkSpace\JuneCRMProject\src\test\resources\suiteb.xlsx (The system cannot find the file specified)">
      <![CDATA[java.io.FileNotFoundException: D:\AprilWorkSpace\JuneCRMProject\src\test\resources\suiteb.xlsx (The system cannot find the file specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.project.JuneCRMProject.utils.ExcelAPI.<init>(ExcelAPI.java:33)
at com.project.JuneCRMProject.BaseClass.BaseTest.init(BaseTest.java:60)
at com.project.JuneCRMProject.BaseClass.BaseTest.beforeTest(BaseTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:64)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:364)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:318)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:620)
at org.testng.TestRunner.beforeRun(TestRunner.java:610)
at org.testng.TestRunner.run(TestRunner.java:581)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeTest -->
  <system-out/>
  <testcase name="f" time="0.000" classname="com.project.JuneCRMProject.suiteb.NewTest">
    <skipped/>
  </testcase> <!-- f -->
  <system-out/>
</testsuite> <!-- com.project.JuneCRMProject.suiteb.NewTest -->
